### ISSUE TITLE
.party machine broke

### ISSUE THREAD

**Issue by iandioch** [cpssd-students/steely#190]
```
⁣⁣Exception in thread Thread-354:
⁣⁣Traceback (most recent call last):
⁣⁣  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
⁣⁣    self.run()
⁣⁣  File "/usr/lib/python3.6/threading.py", line 864, in run
⁣⁣    self._target(*self._args, **self._kwargs)
⁣⁣  File "plugins/parrot.py", line 53, in main
⁣⁣    party(bot, message, image_send, text_send)
⁣⁣  File "plugins/parrot.py", line 41, in party
⁣⁣    image_send(party_url)
⁣⁣  File "plugins/parrot.py", line 49, in <lambda>
⁣⁣    thread_type=thread_type)
⁣⁣  File "/home/senan/.virtualenvs/steely/lib/python3.6/site-packages/fbchat/client.py", line 1018, in sendRemoteImage
⁣⁣    image_id = self._uploadImage(image_url, remote_image, mimetype)
⁣⁣  File "/home/senan/.virtualenvs/steely/lib/python3.6/site-packages/fbchat/client.py", line 978, in _uploadImage
⁣⁣    }, fix_request=True, as_json=True)
⁣⁣  File "/home/senan/.virtualenvs/steely/lib/python3.6/site-packages/fbchat/client.py", line 158, in _postFile
⁣⁣    raise e
⁣⁣  File "/home/senan/.virtualenvs/steely/lib/python3.6/site-packages/fbchat/client.py", line 154, in _postFile
⁣⁣    return check_request(r, as_json=as_json)
⁣⁣  File "/home/senan/.virtualenvs/steely/lib/python3.6/site-packages/fbchat/utils.py", line 205, in check_request
⁣⁣    check_json(j)
⁣⁣  File "/home/senan/.virtualenvs/steely/lib/python3.6/site-packages/fbchat/utils.py", line 184, in check_json
⁣⁣    raise FBchatFacebookError('Error #{} when sending request: {}'.format(j['error'], j['errorDescription']), fb_error_code=j['error'], fb_error_message=j['errorDescription'])
⁣⁣fbchat.models.FBchatFacebookError: Error #1545026 when sending request: The type of file you're trying to attach isn't allowed. Please try again with a different format.
```

I think it might be because the party API URL isn't obviously an image, doesn't end in .png or something.

**Comment by iandioch** [comment]
```
Exception in thread Thread-183:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "plugins/parrot.py", line 53, in main
    party(bot, message, image_send, text_send)
  File "plugins/parrot.py", line 36, in party
    image = grab_image(message)
  File "plugins/parrot.py", line 28, in grab_image
    for a in message.attachments:
AttributeError: 'Message' object has no attribute 'attachments'
```

**Comment by iandioch** [comment]
closing because dupe of #203
